version: '3.7'
services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - 80
  proxy:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/private
    ports:
      - 443:443
  modsec:
    image: owasp/modsecurity-crs:apache
    ports:
      - 8080:80
    environment:
      - BACKEND=http://dvwa:80
      - PROXY=1
