- hosts: localhost
  become: true
  tasks:
    - name: Update apt and install required packages
      apt:
        pkg: 
          - docker.io 
          - docker-compose
          - git
        state: latest
        update_cache: true

    - name: Clone Git Repo
      git:
        repo: https://github.com/spencerroth3/CSEC731.git
        dest: ~/roth-731/
        clone: yes
        update: yes

    - name: Launch containers
      shell: docker-compose up -d  
      args:
        chdir:  ~/roth-731/Project3/docker
